### ISSUE TITLE
Create GeoAlchemy definitions for a basic test Model.

### ISSUE THREAD

**Issue by robertpyke** [BCCVL/BCCVL_Visualiser#2]
Model should contain the following columns:
- geometry (A PostGIS geometry column)
- title (string (255 chars) )
- description (text)
- created_at (datetime)
- updated_at (datetime)

**Comment by prologic** [comment]
Why am I still getting notifications?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
